feat: remove tpw managers env
decentraland/builder-server pull request #366
Opened 2021-11-25 15:00 UTC by nicosantangelo

Closes #365

2021-12-31 13:09 UTC, LautaroPetaccio requested changes

2021-12-31 13:09 UTC, LautaroPetaccio commented on src/Collection/Collection.service.spec.ts
> +      it('should return true', async () => {
```suggestion
      it('should return false', async () => {
```

2022-01-03 22:42 UTC, nicosantangelo commented
@LautaroPetaccio updated

2022-01-04 15:46 UTC, LautaroPetaccio approved these changes

2022-01-04 15:46 UTC, merged