feat: Add support to PUT items by URN
decentraland/builder-server pull request #499
Opened 2022-04-19 18:02 UTC by juanmahidalgo

Close #489

2022-04-19 23:24 UTC, LautaroPetaccio requested changes

2022-04-19 23:24 UTC, LautaroPetaccio commented on src/Item/Item.service.ts
> +        )
If we don't fail when we're updating an item by URN and the item doesn't exist in the DB, we won't be able to tell the user that the editing process failed as it's always going to be creating a new item.
How does `upsertThirdPartyItem` behave when the item id and the item don't exist?

2022-04-20 22:01 UTC, LautaroPetaccio requested changes
There's a merge conflict to be solved, would you mind solving it before I can do the final review?

2022-04-21 13:10 UTC, juanmahidalgo commented on src/Item/Item.router.spec.ts
> +import { omit } from 'decentraland-commons/dist/utils'
done!

2022-04-21 13:10 UTC, juanmahidalgo commented on src/Item/Item.router.spec.ts
> +        describe('and the item is being inserted by URN as param in the URI', () => {
good catch! fixed!

2022-04-21 15:11 UTC, LautaroPetaccio commented on src/Item/Item.router.ts
> +    if ((id && id !== itemJSON.id) || (urn && urn !== itemJSON.urn)) {
The user won't be able to edit URNs in bullk.

2022-04-21 15:13 UTC, LautaroPetaccio approved these changes

2022-04-21 15:58 UTC, merged