feat: Remove rarities with oracle FF
decentraland/builder-server pull request #572
Opened 2022-07-26 20:27 UTC by fzavalia

2022-07-27 18:22 UTC, LautaroPetaccio requested changes

2022-07-27 18:22 UTC, LautaroPetaccio commented on src/Rarity/Rarity.router.spec.ts
> +      )
```suggestion
      mockGetRarityFromBlockchain.mockRejectedValueOnce(new Error('Atahualpa Yupanqui')
      )
```

2022-07-27 18:22 UTC, LautaroPetaccio commented on src/Rarity/utils.ts
> -  return env.get<string | undefined>('FF_RARITIES_WITH_ORACLE') === '1'
Would you mind removing the `FF_RARITIES_WITH_ORACLE` env variables from the CI and from the example?

2022-07-28 16:05 UTC, fzavalia commented
@LautaroPetaccio Reverted the suggestion because that function is being called multiple times and using "Once" will just mock it 1 time.

It is cleared on the root before each so it will not cause any problems.

Changed it to mockRejectedValue instead of the previous mockImplementation still.

2022-07-28 16:47 UTC, LautaroPetaccio requested changes

2022-07-28 16:47 UTC, LautaroPetaccio commented on src/Rarity/Rarity.router.spec.ts
> +    }
As this is building the context, would you mind putting it into a `beforeEach`?

2022-07-28 16:47 UTC, LautaroPetaccio commented on src/Rarity/Rarity.router.spec.ts
> +      )
Same as before, would you mind placing the mock in a `beforeEach`?

2022-07-28 16:47 UTC, LautaroPetaccio commented on src/Rarity/Rarity.router.spec.ts
> +      price: priceMana,
Same as before.

2022-07-28 17:32 UTC, LautaroPetaccio approved these changes

2022-07-28 17:41 UTC, merged