feat: Support filter collections by type
decentraland/builder-server pull request #612
Opened 2022-11-03 20:51 UTC by kevinszuchet

Closes #1724

2022-11-03 21:19 UTC, cyaiox requested changes

2022-11-03 21:19 UTC, cyaiox commented on src/Collection/Collection.types.ts
> +}
np: missing end of line

2022-11-08 15:12 UTC, juanmahidalgo commented on src/Collection/Collection.model.ts
> +      'collections.third_party_id is NULL AND collections.urn_suffix is NULL'
```suggestion
      SQL`collections.third_party_id is NULL AND collections.urn_suffix is NULL`
```
Let's wrap it up with the `SQL` method so we don't have to use the `raw` down below :)

2022-11-08 15:14 UTC, juanmahidalgo commented on src/Collection/Collection.model.ts
> +          ? SQL`(collection_curations.status = ${status} AND (collections.contract_address = ANY(${remoteIds}) OR ${raw(
I really like what you did to re-use the SQL statements above, I was wondering if we can do the same for 
`collections.contract_address = ANY(${remoteIds}`
maybe we can have one variable like the following and re-use it among the queries
```
const isInRemoteIds = SQL`collections.contract_address = ANY(${remoteIds}`
```

2022-11-08 15:16 UTC, juanmahidalgo commented on src/Collection/Collection.model.ts
> +          ? SQL`${raw(isStandard)}`
```suggestion
          ? isStandard
```
these won't be needed anymore if we wrap the variables with the `SQL`

2022-11-08 16:37 UTC, juanmahidalgo approved these changes
LGTM! great job 🚀

2022-11-09 13:47 UTC, cyaiox approved these changes
🚀

2022-11-14 11:42 UTC, merged